var lay_id = layer_get_id("Backgrounds_1")
var back_id = layer_background_get_id(lay_id)
var lay_id2 = layer_get_id("Backgrounds_2")
var back_id2 = layer_background_get_id(lay_id2)
var lay_id3 = layer_get_id("Backgrounds_3")
var back_id3 = layer_background_get_id(lay_id3)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 819)
    layer_background_sprite(back_id, 821)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 834)
    layer_background_sprite(back_id, 833)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 831)
    layer_background_sprite(back_id, 832)
if (global.panic == 1 && layer_background_get_sprite(back_id3) == 836)
    layer_background_sprite(back_id3, 837)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 810)
    layer_background_sprite(back_id, 811)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 813)
    layer_background_sprite(back_id, 814)
if (global.panic == 1 && layer_background_get_sprite(back_id2) == 815)
    layer_background_sprite(back_id2, 816)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 857)
    layer_background_sprite(back_id, 858)
if (global.panic == 1 && layer_background_get_sprite(back_id2) == 855)
    layer_background_sprite(back_id2, 856)
if (global.panic == 1 && layer_background_get_sprite(back_id3) == 853)
    layer_background_sprite(back_id3, 854)
